### ISSUE TITLE
Error constructing xtf with ili2pg.jar

### ISSUE THREAD

**Issue by juusechec** [claeis/ili2db#173]
I'm having error "Caused by: java.lang.ClassNotFoundException: javax.xml.ws.Holder" in construct process of xtf from a postgres schema. 
```
java -jar /home/jorge/Downloads/ili2pg-3.11.3/ili2pg.jar --export --modeldir "/home/jorge/workspace/LADM_COL/Catastro_Multiproposito;/home/jorge/workspace/LADM_COL/ISO" --dbhost localhost --dbusr usuario_ladm_col --dbpwd "****" --dbdatabase ladm_col --dbschema test_ladm_col --models Catastro_Registro_Nucleo_V2_2_1 /home/jorge/Desktop/datos_construccion.xtf
Info: dburl <jdbc:postgresql://localhost/ladm_col>
Info: dbusr <usuario_ladm_col>
Info: ili2pg-3.11.3-20180413
Info: ili2c-4.7.7-20180208
Info: iox-ili-1.20.2-b58e2371ea1155aa3e4f5ff0b86d2432824b151b
Info: java.version 10.0.1
Info: user.name <jorge>
Info: maxMemory 4046848 KB
Info: currentTime 2018-05-15 18:24:12
Info: dbschema <test_ladm_col>
Info: dburl <jdbc:postgresql://localhost/ladm_col>
Info: dbusr <usuario_ladm_col>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.6.8>
Info: driverName <PostgreSQL Native Driver>
Info: driverVersion <PostgreSQL 9.4.1208.jre6>
Info: postGISVersion <POSTGIS="2.4.4 r16526" PGSQL="96" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 1.11.4, released 2016/01/25" LIBXML="2.9.1" LIBJSON="0.11" RASTER>
Info: compile models...
Info: lookup model <Catastro_Registro_Nucleo_V2_2_1> in repository </home/jorge/workspace/LADM_COL/Catastro_Multiproposito>
Info: lookup model <ISO19107_V1_MAGNABOG> 2.3 in repository </home/jorge/workspace/LADM_COL/Catastro_Multiproposito>
Info: lookup model <ISO19107_V1_MAGNABOG> 2.3 in repository </home/jorge/workspace/LADM_COL/ISO>
Info: lookup model <LADM_COL_V1_1> 2.3 in repository </home/jorge/workspace/LADM_COL/Catastro_Multiproposito>
Info: lookup model <LADM_COL_V1_1> 2.3 in repository </home/jorge/workspace/LADM_COL/ISO>
Info: ilifile </home/jorge/workspace/LADM_COL/ISO/ISO19107_V1_MAGNABOG.ili>
Info: ilifile </home/jorge/workspace/LADM_COL/ISO/LADM_COL_V1_1.ili>
Info: ilifile </home/jorge/workspace/LADM_COL/Catastro_Multiproposito/Catastro_Registro_Nucleo_V2_2_1.ili>
Info: process data...
Info: data </home/jorge/Desktop/datos_construccion.xtf>
Info: assume unknown/external objects
Info: first validation pass...
Info: LADM_COL_V1_1.LADM_Nucleo.COL_FuenteAdministrativa...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_UnidadEspacial...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_AgrupacionUnidadesEspaciales...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_EspacioJuridicoUnidadEdificacion...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_EspacioJuridicoRedServicios...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_Nivel...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_RelacionNecesariaUnidadesEspaciales...
Info: LADM_COL_V1_1.LADM_Nucleo.relacionUe...
Info: LADM_COL_V1_1.LADM_Nucleo.ueUeGrupo...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_BAUnit...
Info: LADM_COL_V1_1.LADM_Nucleo.rrrFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_RelacionNecesariaBAUnits...
Info: LADM_COL_V1_1.LADM_Nucleo.ueBaunit...
Info: LADM_COL_V1_1.LADM_Nucleo.relacionBaunit...
Info: LADM_COL_V1_1.LADM_Nucleo.relacionFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.unidadFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_Punto...
Info: LADM_COL_V1_1.LADM_Nucleo.COL_FuenteEspacial...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_CadenaCarasLimite...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_CarasLindero...
Info: LADM_COL_V1_1.LADM_Nucleo.puntoFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.ueFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.baunitFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.relacionFuenteUespacial...
Info: LADM_COL_V1_1.LADM_Nucleo.cclFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.menos...
Info: LADM_COL_V1_1.LADM_Nucleo.masCcl...
Info: LADM_COL_V1_1.LADM_Nucleo.puntoCcl...
Info: LADM_COL_V1_1.LADM_Nucleo.clFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.menosf...
Info: LADM_COL_V1_1.LADM_Nucleo.mas...
Info: LADM_COL_V1_1.LADM_Nucleo.puntoCl...
Info: LADM_COL_V1_1.LADM_Nucleo.LA_Agrupacion_Interesados...
Info: LADM_COL_V1_1.LADM_Nucleo.baunitComoInteresado...
Info: LADM_COL_V1_1.LADM_Nucleo.responsableFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.topografoFuente...
Info: LADM_COL_V1_1.LADM_Nucleo.miembros...
Info: Catastro_Registro_Nucleo_V2_2_1.Catastro_Registro.COL_Derecho...
Info: Catastro_Registro_Nucleo_V2_2_1.Catastro_Registro.Construccion...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/ws/Holder
	at ch.interlis.iom_j.itf.impl.ItfSurfaceLinetable2Polygon.createLineset(ItfSurfaceLinetable2Polygon.java:292)
	at ch.interlis.iom_j.itf.impl.ItfSurfaceLinetable2Polygon.validatePolygon(ItfSurfaceLinetable2Polygon.java:273)
	at ch.interlis.iox_j.validator.Validator.validateSurfaceTopology(Validator.java:2921)
	at ch.interlis.iox_j.validator.Validator.validateAttrValue(Validator.java:2838)
	at ch.interlis.iox_j.validator.Validator.validateObject(Validator.java:2388)
	at ch.interlis.iox_j.validator.Validator.validateAttrValue(Validator.java:2694)
	at ch.interlis.iox_j.validator.Validator.validateObject(Validator.java:2388)
	at ch.interlis.iox_j.validator.Validator.validateAttrValue(Validator.java:2694)
	at ch.interlis.iox_j.validator.Validator.validateObject(Validator.java:2388)
	at ch.interlis.iox_j.validator.Validator.validate(Validator.java:272)
	at ch.ehi.ili2db.toxtf.TransferToXtf.dumpObjHelper(Unknown Source)
	at ch.ehi.ili2db.toxtf.TransferToXtf.dumpObject(Unknown Source)
	at ch.ehi.ili2db.toxtf.TransferToXtf.doBasket(Unknown Source)
	at ch.ehi.ili2db.toxtf.TransferToXtf.doit(Unknown Source)
	at ch.ehi.ili2db.base.Ili2db.transferToXtf(Unknown Source)
	at ch.ehi.ili2db.base.Ili2db.runExport(Unknown Source)
	at ch.ehi.ili2db.base.Ili2db.run(Unknown Source)
	at ch.ehi.ili2db.AbstractMain.domain(Unknown Source)
	at ch.ehi.ili2pg.PgMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.Holder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 19 more
```

**Comment by juusechec** [comment]
It's for java version.
