### ISSUE TITLE
Export: java.lang.NumberFormatException / ch.interlis.iox_j.validator.Validator.roundNumeric

### ISSUE THREAD

**Issue by edigonzales** [claeis/ili2db#367]
While exporting I get the following error.

- Is it related to `arp_npl_pub.nutzungsplanung_ueberlagernd_linie`?
- Is it an error in the geometry?

```
Info: data </tmp/gretl-share/agidataexport-73aa148a-f7d8-4e51-83f6-dd2f5ac3c60f/ch.so.arp.nutzungsplanung_2020-09-24.xtf>
Info: SO_Nutzungsplanung_Publikation_20190909.Nutzungsplanung BID <SO_Nutzungsplanung_Publikation_20190909.Nutzungsplanung>...
Info: SO_Nutzungsplanung_Publikation_20190909.Nutzungsplanung.Grundnutzung...
Info: dumpObjHelper(): SELECT r0.T_Id, r0.T_Ili_Tid,r0.typ_bezeichnung,r0.typ_abkuerzung,r0.typ_verbindlichkeit,r0.typ_bemerkungen,r0.typ_kt,r0.typ_code_kommunal,r0.typ_nutzungsziffer,r0.typ_nutzungsziffer_art,r0.typ_geschosszahl,ST_AsEWKB(r0.geometrie),r0.name_nummer,r0.rechtsstatus,r0.publiziert_ab,r0.bemerkungen,r0.erfasser,r0.datum_erfassung,cast(r0.dokumente as text),r0.bfs_nr FROM arp_npl_pub.nutzungsplanung_grundnutzung r0 (TransferToXtf.java:998)
Info: SO_Nutzungsplanung_Publikation_20190909.Nutzungsplanung.Ueberlagernd_Flaeche...
Info: dumpObjHelper(): SELECT r0.T_Id, r0.T_Ili_Tid,r0.typ_bezeichnung,r0.typ_abkuerzung,r0.typ_verbindlichkeit,r0.typ_bemerkungen,r0.typ_kt,r0.typ_code_kommunal,ST_AsEWKB(r0.geometrie),r0.name_nummer,r0.rechtsstatus,r0.publiziert_ab,r0.bemerkungen,r0.erfasser,r0.datum_erfassung,cast(r0.dokumente as text),r0.bfs_nr FROM arp_npl_pub.nutzungsplanung_ueberlagernd_flaeche r0 (TransferToXtf.java:998)
Info: SO_Nutzungsplanung_Publikation_20190909.Nutzungsplanung.Ueberlagernd_Linie...
Info: dumpObjHelper(): SELECT r0.T_Id, r0.T_Ili_Tid,r0.typ_bezeichnung,r0.typ_abkuerzung,r0.typ_verbindlichkeit,r0.typ_bemerkungen,r0.typ_kt,r0.typ_code_kommunal,ST_AsEWKB(r0.geometrie),r0.name_nummer,r0.rechtsstatus,r0.publiziert_ab,r0.bemerkungen,r0.erfasser,r0.datum_erfassung,cast(r0.dokumente as text),r0.bfs_nr FROM arp_npl_pub.nutzungsplanung_ueberlagernd_linie r0 (TransferToXtf.java:998)
failed to run ili2pg
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:494)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:806)
	at ch.interlis.iox_j.validator.Validator.roundNumeric(Validator.java:4021)
	at ch.interlis.iox_j.filter.Rounder.roundNumber(Rounder.java:170)
	at ch.interlis.iox_j.filter.Rounder.roundSegment(Rounder.java:161)
	at ch.interlis.iox_j.filter.Rounder.roundLine(Rounder.java:148)
	at ch.interlis.iox_j.filter.Rounder.roundAttrValue(Rounder.java:114)
	at ch.interlis.iox_j.filter.Rounder.roundObject(Rounder.java:84)
	at ch.interlis.iox_j.filter.Rounder.filter(Rounder.java:62)
	at ch.ehi.ili2db.toxtf.TransferToXtf.dumpObjHelper(TransferToXtf.java:1050)
	at ch.ehi.ili2db.toxtf.TransferToXtf.dumpObject(TransferToXtf.java:990)
	at ch.ehi.ili2db.toxtf.TransferToXtf.doBasket(TransferToXtf.java:474)
	at ch.ehi.ili2db.toxtf.TransferToXtf.doit(TransferToXtf.java:276)
	at ch.ehi.ili2db.base.Ili2db.transferToXtf(Ili2db.java:2288)
	at ch.ehi.ili2db.base.Ili2db.runExport(Ili2db.java:1705)
	at ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:223)
```

**Comment by edigonzales** [comment]
Originalgeometrie:
```
<SO_Nutzungsplanung_20171118.Nutzungsplanung.Ueberlagernd_Linie TID="71F45411-370B-47D9-959D-9F0BCCF735D8"><Geometrie><POLYLINE><COORD><C1>2608685.764</C1><C2>1250628.214</C2></COORD><ARC><C1>2608685.916</C1><C2>1250628.013</C2><A1>2608685.839366304</A1><A2>1250628.1130207872</A2></ARC><COORD><C1>2608685.92</C1><C2>1250628.008</C2></COORD><COORD><C1>2608685.939</C1><C2>1250627.984</C2></COORD><COORD><C1>2608686.044</C1><C2>1250627.851</C2></COORD><COORD><C1>2608686.105</C1><C2>1250627.777</C2></COORD><COORD><C1>2608686.107</C1><C2>1250627.775</C2></COORD><COORD><C1>2608686.115</C1><C2>1250627.766</C2></COORD><COORD><C1>2608686.211</C1><C2>1250627.651</C2></COORD><COORD><C1>2608686.229</C1><C2>1250627.631</C2></COORD><COORD><C1>2608686.284</C1><C2>1250627.566</C2></COORD><COORD><C1>2608686.288</C1><C2>1250627.562</C2></COORD><COORD><C1>2608686.293</C1><C2>1250627.557</C2></COORD><COORD><C1>2608686.396</C1><C2>1250627.44</C2></COORD><COORD><C1>2608686.435</C1><C2>1250627.398</C2></COORD><COORD><C1>2608686.47</C1><C2>1250627.36</C2></COORD><COORD><C1>2608686.487</C1><C2>1250627.342</C2></COORD><COORD><C1>2608686.574</C1><C2>1250627.249</C2></COORD><COORD><C1>2608686.66</C1><C2>1250627.159</C2></COORD><COORD><C1>2608686.77</C1><C2>1250627.048</C2></COORD><COORD><C1>2608686.839</C1><C2>1250626.981</C2></COORD><COORD><C1>2608686.842</C1><C2>1250626.978</C2></COORD><COORD><C1>2608686.845</C1><C2>1250626.975</C2></COORD><COORD><C1>2608686.866</C1><C2>1250626.956</C2></COORD><COORD><C1>2608686.896</C1><C2>1250626.926</C2></COORD><COORD><C1>2608686.974</C1><C2>1250626.852</C2></COORD><COORD><C1>2608686.976</C1><C2>1250626.85</C2></COORD><COORD><C1>2608686.981</C1><C2>1250626.846</C2></COORD><COORD><C1>2608686.991</C1><C2>1250626.837</C2></COORD><COORD><C1>2608687.025</C1><C2>1250626.805</C2></COORD><COORD><C1>2608687.059</C1><C2>1250626.774</C2></COORD><COORD><C1>2608687.066</C1><C2>1250626.767</C2></COORD><COORD><C1>2608687.067</C1><C2>1250626.766</C2></COORD><COORD><C1>2608687.069</C1><C2>1250626.764</C2></COORD><COORD><C1>2608687.202</C1><C2>1250626.645</C2></COORD><COORD><C1>2608687.265</C1><C2>1250626.59</C2></COORD><COORD><C1>2608687.268</C1><C2>1250626.588</C2></COORD><COORD><C1>2608687.275</C1><C2>1250626.582</C2></COORD><ARC><C1>2608687.409</C1><C2>1250626.468</C2><A1>2608687.3416875135</A1><A2>1250626.5246326916</A2></ARC><COORD><C1>2608687.434</C1><C2>1250626.446</C2></COORD><COORD><C1>2608687.459</C1><C2>1250626.426</C2></COORD><COORD><C1>2608687.477</C1><C2>1250626.411</C2></COORD><COORD><C1>2608687.481</C1><C2>1250626.408</C2></COORD><COORD><C1>2608687.497</C1><C2>1250626.395</C2></COORD><COORD><C1>2608687.524</C1><C2>1250626.373</C2></COORD><COORD><C1>2608687.542</C1><C2>1250626.358</C2></COORD><ARC><C1>2608687.694</C1><C2>1250626.239</C2><A1>2608687.617677025</A1><A2>1250626.2980874602</A2></ARC><ARC><C1>2608693.125</C1><C2>1250624.173</C2><A1>2608690.2560036946</A1><A2>1250624.8024964014</A2></ARC><COORD><C1>2608693.129</C1><C2>1250624.173</C2></COORD><COORD><C1>2608699.453</C1><C2>1250623.768</C2></COORD><COORD><C1>2608702.866</C1><C2>1250623.094</C2></COORD><COORD><C1>2608715.236</C1><C2>1250620.653</C2></COORD><COORD><C1>2608720.42</C1><C2>1250618.913</C2></COORD><COORD><C1>2608728.71</C1><C2>1250616.129</C2></COORD><COORD><C1>2608728.711</C1><C2>1250616.129</C2></COORD><COORD><C1>2608730.01</C1><C2>1250615.693</C2></COORD><COORD><C1>2608741.571</C1><C2>1250611.261</C2></COORD></POLYLINE></Geometrie><Rechtsstatus>inKraft</Rechtsstatus><publiziertAb>1900-01-01</publiziertAb><Datum>1900-01-01</Datum><Typ_Ueberlagernd_Linie REF="4F137561-DF79-4958-959C-1AF2815F7C74"></Typ_Ueberlagernd_Linie></SO_Nutzungsplanung_20171118.Nutzungsplanung.Ueberlagernd_Linie>
```

Geometrie nach Import mit ili2pg (--strokeArcs):
```
LINESTRING (2608685.764 1250628.214, 2608685.839 1250628.113, 2608685.916 1250628.013, 2608685.92 1250628.008, 2608685.939 1250627.984, 2608686.044 1250627.851, 2608686.105 1250627.777, 2608686.107 1250627.775, 2608686.115 1250627.766, 2608686.211 1250627.651, 2608686.229 1250627.631, 2608686.284 1250627.566, 2608686.288 1250627.562, 2608686.293 1250627.557, 2608686.396 1250627.44, 2608686.435 1250627.398, 2608686.47 1250627.36, 2608686.487 1250627.342, 2608686.574 1250627.249, 2608686.66 1250627.159, 2608686.77 1250627.048, 2608686.839 1250626.981, 2608686.842 1250626.978, 2608686.845 1250626.975, 2608686.866 1250626.956, 2608686.896 1250626.926, 2608686.974 1250626.852, 2608686.976 1250626.85, 2608686.981 1250626.846, 2608686.991 1250626.837, 2608687.025 1250626.805, 2608687.059 1250626.774, 2608687.066 1250626.767, 2608687.067 1250626.766, 2608687.069 1250626.764, 2608687.202 1250626.645, 2608687.265 1250626.59, 2608687.268 1250626.588, 2608687.275 1250626.582, NaN NaN, NaN NaN, NaN NaN, 2608687.342 1250626.525, NaN NaN, NaN NaN, NaN NaN, 2608687.409 1250626.468, 2608687.434 1250626.446, 2608687.459 1250626.426, 2608687.477 1250626.411, 2608687.481 1250626.408, 2608687.497 1250626.395, 2608687.524 1250626.373, 2608687.542 1250626.358, 2608687.618 1250626.298, 2608687.694 1250626.239, 2608687.9080984876 1250626.077783644, 2608688.12644805 1250625.9223733982, 2608688.348891276 1250625.7728813007, 2608688.575267802 1250625.6294151223, 2608688.80541443 1250625.49207829, 2608689.039165244 1250625.3609698126, 2608689.276351729 1250625.2361842077, 2608689.5168028935 1250625.1178114354, 2608689.7603453933 1250625.0059368322, 2608690.0068036537 1250624.9006410507, 2608690.256 1250624.802, 2608690.507725086 1250624.7100951844, 2608690.761826577 1250624.6249808727, 2608691.0181213315 1250624.5467184107, 2608691.276424625 1250624.475364206, 2608691.5365502867 1250624.4109696865, 2608691.7983108317 1250624.3535812644, 2608692.061517597 1250624.3032403023, 2608692.3259808784 1250624.2599830832, 2608692.5915100635 1250624.2238407847, 2608692.857913774 1250624.1948394561, 2608693.125 1250624.173, 2608693.129 1250624.173, 2608699.453 1250623.768, 2608702.866 1250623.094, 2608715.236 1250620.653, 2608720.42 1250618.913, 2608728.71 1250616.129, 2608728.711 1250616.129, 2608730.01 1250615.693, 2608741.571 1250611.261)
```

-> Die NaN sind das Problem. Mit --disableRounding wird exportiert.

**Comment by edigonzales** [comment]
Exotischer Workaround:

```
SELECT 
    ST_MakeLine(geom)
from 
(
    SELECT  
        (ST_DumpPoints(geometrie)).* 
    FROM 
        arp_npl.nutzungsplanung_ueberlagernd_linie 
    WHERE 
        t_ili_tid = '71F45411-370B-47D9-959D-9F0BCCF735D8'
) AS dump 
where 
    ST_X(geom) <> 'nan'
```

**Comment by edigonzales** [comment]
Workaround funktioniert so nicht, da Reihenfolge nicht garantiert ist.

**Comment by claeis** [comment]
Die NaN enstehen beim Import, wenn A1,A2 gerundet wird:

	<COORD>
		<C1>2608687.275</C1>
		<C2>1250626.582</C2>
	</COORD>
	<ARC>
		<C1>2608687.409</C1>
		<C2>1250626.468</C2>
		<A1>2608687.3416875135</A1>
		<A2>1250626.5246326916</A2>
	</ARC>
