### ISSUE TITLE
Postgres 13 support

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#371]
When using ili2pg with postgresql 13 (https://hub.docker.com/r/kartoza/postgis/) I get a connection error

```
ec 22, 2020 2:01:58 PM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:614)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ch.ehi.ili2db.base.AbstractJdbcMapping.connect(AbstractJdbcMapping.java:32)
	at ch.ehi.ili2db.base.Ili2db.connect(Ili2db.java:1876)
	at ch.ehi.ili2db.base.Ili2db.readSettingsFromDb(Ili2db.java:183)
	at ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:557)
	at ch.ehi.ili2pg.PgMain.main(PgMain.java:70)

```

**Comment by edigonzales** [comment]
Can you test it with a recent jdbc version? Attached a dist zip with v42.2.18.

[ili2pg-4.4.5-SNAPSHOT.zip](https://github.com/claeis/ili2db/files/5731325/ili2pg-4.4.5-SNAPSHOT.zip)

**Comment by m-kuhn** [comment]
Solves the problem

**Comment by edigonzales** [comment]
Just to be sure and no offence, but you talk to @claeis regarding these issues to find a proper solution?

**Comment by m-kuhn** [comment]
This was a note to self from a random test I performed.

#369 will need a proper fix before going to prod.
