### ISSUE TITLE
[ili2fgdb] UnsatisfiedLinkError: 'long ch.ehi.fgdb4j.jni.fgbd4jJNI.new_Geodatabase()'

### ISSUE THREAD

**Issue by HusseinKabbout** [claeis/ili2db#386]
Beim Versuch `ili2fgdb` unter Linux zum laufen zu bringen bekomme ich folgenden Java stacktrace:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long ch.ehi.fgdb4j.jni.fgbd4jJNI.new_Geodatabase()'
        at ch.ehi.fgdb4j.jni.fgbd4jJNI.new_Geodatabase(Native Method)
        at ch.ehi.fgdb4j.jni.Geodatabase.<init>(Geodatabase.java:139)
        at ch.ehi.ili2fgdb.jdbc.FgdbDriver.connect(FgdbDriver.java:58)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at ch.ehi.ili2db.base.AbstractJdbcMapping.connect(AbstractJdbcMapping.java:31)
        at ch.ehi.ili2db.base.Ili2db.connect(Ili2db.java:1795)
        at ch.ehi.ili2db.base.Ili2db.readSettingsFromDb(Ili2db.java:187)
        at ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:553)
        at ch.ehi.ili2fgdb.FgdbMain.main(FgdbMain.java:70)
```
## Wie bin ich auf diese Fehlermeldung gekommen?

Ich habe [hier](https://github.com/claeis/fgdb4j/blob/master/src/java/ch/ehi/fgdb4j/Fgdb4j.java#L101), den Code so angepasst, dass `Fgdb4j.java` direkt meine `Library` ladet und nicht nach `DLL`-Dateien sucht.

Danach habe ich via `gradle jar` das neue JAR gebaut und für ili2fgdb gebraucht.

## Von wo habe ich meine Library?

Die `Library` habe ich von [hier](https://github.com/Esri/file-geodatabase-api/tree/master/FileGDB_API_1.5.1) heruntergeladen.

Wo könnte hier das Problem sein?

cc: @edigonzales

**Comment by HusseinKabbout** [comment]
Nach ein paar Tests habe ich gemerkt, dass ich nicht `Fgdb4j.java` anpassen müsste, sondern ich kann die `ch.ehi.fgdb4j.esriapi` und `ch.ehi.fgdb4j.wrapper` Properties setzen. Der Rest wird dann richtig gehändelt.

Die Frage stellt sich jetzt: Von wo bekomme ich die wrapper Lib? (Die Library für die `esriapi`, habe ich bereits.)

**Comment by HusseinKabbout** [comment]
Den Wrapper konnte ich mit Hilfe vom `build.gradle` bauen. Dabei musste ich aber ein paar Einstellungen anpassen, da `gradle` sonst die Header-Files nicht gefunden hat.

```
cppCompiler.args "-I"+new File("/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-0.fc33.x86_64/include").getAbsolutePath()
cppCompiler.args "-I"+new File("/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-0.fc33.x86_64/include/linux").getAbsolutePath()
cppCompiler.args "-I"+new File("/tmp/FileGDB_API-64/include").getAbsolutePath()
cppCompiler.args "-I"+new File("/tmp/fgdb4j/src/swig").getAbsolutePath()
```

Die Wrapper Library habe ich dann wie folgt gebaut:

```
swig -o gensrc/cpp/fgdb4j.cxx -oh gensrc/cpp/fgdb4j.h -I/tmp/FileGDB_API-64/include -c++ -java -outdir gensrc/java/ch/ehi/fgdb4j/jni -package ch.ehi.fgdb4j.jni src/swig/fgdb4j.i
gradle fgdb4jX64SharedLibrary
ln -s /tmp/fgdb4j/build/libs/fgdb4j/shared/x64/libfgdb4j.so /usr/lib64
```

Beim laden der `.so` Datei kommt aber folgender Fehler:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/fgdb4j/build/libs/fgdb4j/shared/x64/libfgdb4j.so: /tmp/build/libs/fgdb4j/shared/x64/libfgdb4j.so: undefined symbol: _ZTIN10FileGDBAPI11ShapeBufferE
```

**Comment by claeis** [comment]
see https://github.com/claeis/fgdb4j

But so far I was not able to create a travis script that builds the windows and linux (and mac) variants of the native library.

**Comment by HusseinKabbout** [comment]
Dieses Ticket ist nicht mehr relevant für mich, daher schliesse ich es.
