### ISSUE TITLE
ExceptionInitializerError with ili2pg-4.4.4.jar

### ISSUE THREAD

**Issue by m-kuhn** [claeis/ili2db#406]
On a macOS system.
Interestingly the last log message is related to `http` (not `https`)

```
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Exception in thread "main"
java.lang.ExceptionInInitializerError
at javax.crypto.Cipher.getInstance(Cipher.java:518)
at sun.security.ssl.JsseJce.getCipher(JsseJce.java:189)
at sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:483)
at sun.security.ssl.SSLCipher.<init>(SSLCipher.java:472)
at sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:81)
at sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:67)
at
sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:345)
at sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:46)
at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>
(SSLContextImpl.java:577)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at java.security.Provider$Service.getImplClass(Provider.java:1728)
at java.security.Provider$Service.newInstance(Provider.java:1686)
at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
at
javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>
(HttpsURLConnectionImpl.java:99)
at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
at java.net.URL.openConnection(URL.java:1001)
at
ch.interlis.ilirepository.impl.RepositoryAccess.getLocalFileLocation(RepositoryAccess.java:1430)
at ch.interlis.ilirepository.IliManager.createConfig(IliManager.java:410)
at ch.interlis.ilirepository.IliManager.getConfigWithFiles(IliManager.java:256)
at ch.interlis.ili2c.Main.runCompiler(Main.java:642)
at ch.ehi.ili2db.base.Ili2db.runUpdate(Ili2db.java:487)
at ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:215)
at ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:554)
at ch.ehi.ili2pg.PgMain.main(PgMain.java:70)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:93)
... 32 more

Caused by: java.lang.SecurityException: The jurisdiction policy files are not signed by the
expected signer! (Policy files are specific per major JDK release.Ensure the correct version is
installed.)
at javax.crypto.JarVerifier.verifyPolicySigned(JarVerifier.java:336)
at javax.crypto.JceSecurity.loadPolicies(JceSecurity.java:378)
at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:323)
at javax.crypto.JceSecurity.access$000(JceSecurity.java:50)
at javax.crypto.JceSecurity$1.run(JceSecurity.java:85)
at java.security.AccessController.doPrivileged(Native Method)
at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:82)
... 32 more
Finished (1)
```

**Comment by edigonzales** [comment]
ili2pg v4.4.4

**Comment by m-kuhn** [comment]
Fixed by updating java

**Comment by m-kuhn** [comment]
For reference:

Borken java version was 1.8.0_281-b09
![image](https://user-images.githubusercontent.com/588407/119675150-146e7d80-be3d-11eb-8d83-233484c33ef5.png)

**Comment by edigonzales** [comment]
For Linux/macOS I recommend https://sdkman.io/install
